GET {{API_HOST}}/leagues
Accept: application/json

###

GET {{API_HOST}}/leagues/{{LEAGUE_ID}}
Accept: application/json

###

POST {{API_HOST}}/leagues
Content-Type: application/json

{
  "name": "my new league 1"
}

###

POST {{API_HOST}}/leagues/{{LEAGUE_ID}}/join
Content-Type: application/json
Accept: application/json

{
  "name": "James"
}

###
